feat(middleware-code-coverage): enable frontend watermarks configuration
SAP/ui5-tooling-extensions pull request #145
Opened 2023-08-31 10:36 UTC by d3xter666

This feature enables the extension of default or ui5.yaml's Istanbul configuration, so that certain settings could be adjusted from the frontend.

JIRA: CPOUI5FOUNDATION-709

2023-09-01 10:39 UTC, flovogt requested changes

2023-09-01 10:39 UTC, flovogt commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +					},
here we have now whitespaces before the properties... should be cleaned up

2023-09-01 10:39 UTC, flovogt commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +test("Report Coverage (old structure)- backwards compatibility", async (t) => {
```suggestion
test("Report Coverage (old structure)", async (t) => {
```

2023-09-01 10:39 UTC, flovogt commented on packages/middleware-code-coverage/README.md
> +**Note:** Some report settings could be adjusted from the frontend by providing the setting via the request body. Currently, only [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b45
```suggestion
**Note:** Also it is possible to set report settings from the frontend by providing them via the request body. Currently, only [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b458789a746dff2abd3e2e4790c3/README.md#high-and-low-watermarks) are supported. Frontend defined settings take precedence over default or `ui5.yaml` configured ones.
```

2023-09-04 13:05 UTC, flovogt approved these changes
LGTM

2023-09-04 13:06 UTC, flovogt commented
@matz3 any further comments?

2023-09-04 14:57 UTC, matz3 requested changes

2023-09-04 14:57 UTC, matz3 commented on packages/middleware-code-coverage/lib/coverage-reporter.js
> +	reportConfig.watermarks = {...reportConfig.watermarks, ...watermarks};
Is it intended that the default watermarks configuration is persistently modified and not only taken into account for the single report but for every new report created until a different watermarks configuration overwrites it again?

The expected behaviour should be ensured via tests.
I see that there are actually no new tests that cover the new watermarks property.

2023-09-04 14:57 UTC, matz3 commented on packages/middleware-code-coverage/README.md
> +  body: JSON.stringify({
Please also update the other example for a request to use the new format.

2023-09-05 12:01 UTC, d3xter666 commented on packages/middleware-code-coverage/lib/coverage-reporter.js
> +	reportConfig.watermarks = {...reportConfig.watermarks, ...watermarks};
There is always a `watermarks` config, regardless if it's the default one, the one from `ui5.yaml` or the one that comes from the frontend. Basically, this is the precedence. 

Please take a look [here](https://github.com/SAP/ui5-tooling-extensions/blob/f56fd1dc4c569bfc76dfee0b02e122b33cf97ea3/packages/middleware-code-coverage/lib/coverage-reporter.js#L71). The `context` always relies on the `watermarks`, nevertheless, it's used later when producing the reports and only in certain kinds of reports.

I will write some tests to cover the watermarks behaviour.

2023-09-05 12:05 UTC, matz3 commented on packages/middleware-code-coverage/lib/coverage-reporter.js
> +	reportConfig.watermarks = {...reportConfig.watermarks, ...watermarks};
I noticed that when I start a test once with watermarks configuration on client-side and then run another test without any watermarks configuration, it continued to use the watermarks from the first test configuration. I do not think this is expected behavior.

2023-09-05 12:05 UTC, d3xter666 commented on packages/middleware-code-coverage/README.md
> +  body: JSON.stringify({
Thanks!

2023-09-05 12:06 UTC, d3xter666 commented on packages/middleware-code-coverage/lib/coverage-reporter.js
> +	reportConfig.watermarks = {...reportConfig.watermarks, ...watermarks};
Ah, nice catch! Thank you!
I'll check & fix that! It's definitely not what we expect

2023-09-07 19:21 UTC, d3xter666 commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +	reportSpy.resetHistory();
Thanks!

2023-09-07 19:24 UTC, d3xter666 commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +	t.deepEqual(watermarks, reportedWatermarks, "Watermarks got updated");
Done

2023-09-07 19:24 UTC, d3xter666 commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +	t.notDeepEqual(watermarks, reportedWatermarks, "Default watermarks got used");
Done

2023-09-07 19:43 UTC, d3xter666 commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +test("Report Coverage: Fronted config for watermarks", async (t) => {
Done

2023-09-07 19:43 UTC, d3xter666 commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +	t.notDeepEqual(watermarks, reportedWatermarks, "Default watermarks got used");
Done

2023-09-07 19:44 UTC, d3xter666 commented on packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
> +	const reportSpy = sinon.spy(libReport, "createContext");
Thanks!

2023-09-08 07:17 UTC, matz3 reviewed
LGTM

2023-09-14 10:28 UTC, matz3 submitted a review, later dismissed

2023-09-14 10:28 UTC, matz3 commented on packages/middleware-code-coverage/README.md
> +**Note:** Also it is possible to set report settings from the frontend by providing them via the request body. Currently, only [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b45878
While this description is not incorrect, it does not really help a user understanding what to do in order to make use of the feature.
The middleware API is not primarily intended to be used directly, so telling that it can be passed as request body is not relevant.

2023-09-14 10:42 UTC, d3xter666 commented on packages/middleware-code-coverage/README.md
> +**Note:** Also it is possible to set report settings from the frontend by providing them via the request body. Currently, only [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b45878
To me, this becomes a little confusing to understand and structure 🤔 

On one side, there's this API documentation where we list the API endpoints with the payload and on the other side, we know that this won't be used standalone, but with Openui5. We acknowledge that we need to somehow also give suggestions on how to use it.
So, how to structure this?

What do you think if I update the HTML samples in the **Usage** section and reference it from here?

2023-09-15 11:49 UTC, matz3 commented on packages/middleware-code-coverage/README.md
> +      ></script>
indentation doesn't fit to all other lines

2023-09-15 11:49 UTC, matz3 commented on packages/middleware-code-coverage/README.md
> +      ></script>
- indentation doesn't fit to all other lines (same applies to script tag in new section)
- the code above has the same script tag and is not changed, so both are out-of-sync now

2023-09-15 11:49 UTC, matz3 commented on packages/middleware-code-coverage/docs/API.md
> +Copyright 2023 SAP SE or an SAP affiliate company and UI5 Tooling Extensions contributors. Please see our [LICENSE.txt](../../LICENSE.txt) for copyright and license information. Detailed information
Not sure whether we need this for every markdown page. I would expect that it's sufficient in the README.md which serves as the entrypoint for the package.

But at least the relative link to LICENSE.txt should be updated then.

2023-09-15 11:49 UTC, matz3 commented on packages/middleware-code-coverage/README.md
> +  ></script>
Wouldn't it be sufficient and easier to read if we just mention the relevant script tag in here? Everything else is just a copy of the already existing code described above, so nothing that needs to be changed.

2023-09-15 11:49 UTC, matz3 commented on packages/middleware-code-coverage/README.md
> +It is possible to override [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b458789a746dff2abd3e2e4790c3/README.md#high-and-low-watermarks) (since OpenUI5 1.119.0) via data attribute
```suggestion
It is possible to override [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b458789a746dff2abd3e2e4790c3/README.md#high-and-low-watermarks) (since UI5 1.119.0) via data attributes in `qunit-coverage-istanbul.js`'s script tag.
```
We also use `UI5` as a general term already on this page.

2023-09-18 07:00 UTC, d3xter666 commented on packages/middleware-code-coverage/docs/API.md
> +Copyright 2023 SAP SE or an SAP affiliate company and UI5 Tooling Extensions contributors. Please see our [LICENSE.txt](../../LICENSE.txt) for copyright and license information. Detailed information
Thanks! I tought it is mandatory for all the pages. Removing it.

2023-09-18 07:06 UTC, d3xter666 commented on packages/middleware-code-coverage/README.md
> +  ></script>
Maybe GitHub's Diff markdown will fit here best: https://gist.github.com/salmedina/ad8bea4f46de97ea132f71b0bca73663#file-markdowndiffexample-md

2023-09-18 07:38 UTC, matz3 reviewed
LGTM.

Unit tests seem to be unstable.

2023-09-18 08:14 UTC, d3xter666 commented
> Unit tests seem to be unstable.

It's always this one `Tests / Unit and Integration (20, windows-2022) (pull_request)`. I guess it's something with the new Node on wondows. I'll take a look

2023-09-19 07:15 UTC, KlattG requested changes

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/docs/API.md
> +Returns the generated report(s) from the last generation via the `/.ui5/coverage/report` route.
```suggestion
Returns the most recent report(s) via the `/.ui5/coverage/report` route.
```

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/docs/API.md
> +Below is an example of a sample scenario to integrate UI5 Middleware Code Coverage.
```suggestion
Sample scenario to integrate UI5 Middleware Code Coverage:
```

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/README.md
> +### Frontend Configuration
```suggestion
### Front-End Configuration
```

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/README.md
> +It is possible to override [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b458789a746dff2abd3e2e4790c3/README.md#high-and-low-watermarks) (since UI5 1.119.0) via data attributes in
```suggestion
You can override [`watermarks`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b458789a746dff2abd3e2e4790c3/README.md#high-and-low-watermarks) (since UI5 1.119.0) via data attributes in the script tag for `qunit-coverage-istanbul.js`':
```

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/README.md
> +The middleware adds an HTTP endpoint to the development server. Information about the endpoints can be found in the [API document](./docs/API.md).
```suggestion
The middleware adds an HTTP endpoint to the development server. For more information about the endpoints, see the [API document](./docs/API.md).
```

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/README.md
> +The custom middleware intercepts every `.js`-file before it is sent to the client. The file is then instrumented on the fly, including the dynamic creation of a `sourcemap`.
```suggestion
The custom middleware intercepts every `.js`-file before it is sent to the client. The file is then instrumented on the fly, which includes the dynamic creation of a `sourcemap`.
```

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/README.md
> +## How it works
```suggestion
## How It Works
```

2023-09-19 07:15 UTC, KlattG commented on packages/middleware-code-coverage/README.md
> +The middleware is integrated into OpenUI5 out of the box, but it is not limited just to it. With the [configuration](#configuration) and the [public API](./docs/API.md), developers could set up the m
```suggestion
The middleware is integrated into OpenUI5 out of the box, but you are not limited by this. With the [configuration](#configuration) and the [public API](./docs/API.md), you can set up the middleware to suit your projects' needs.
```

2023-09-19 08:53 UTC, KlattG approved these changes
LGTM

2023-09-19 09:53 UTC, flovogt requested changes

2023-09-19 09:53 UTC, flovogt commented on packages/middleware-code-coverage/docs/API.md
> +Sends `__coverage__` data to the middleware. A static report is generated with the data provided. Reports can be accessed via the `/.ui5/coverage/report/${reportType}` route. The available report typ
its not only the coverage data.. with watermarks its even more

2023-09-19 10:34 UTC, d3xter666 commented on packages/middleware-code-coverage/docs/API.md
> +Sends `__coverage__` data to the middleware. A static report is generated with the data provided. Reports can be accessed via the `/.ui5/coverage/report/${reportType}` route. The available report typ
Please, check the notes and the sample below.

If you insist, maybe we can merge them, but it's important that the `watermarks` would be available with `@ui5/middleware-code-coverage` with version `1.1.0` and `UI5` version `1.119.0` and that's why they've been put into a separate Note

2023-09-19 11:02 UTC, flovogt approved these changes

2023-09-19 11:05 UTC, matz3 approved these changes

2023-09-19 11:07 UTC, merged