build: add missing supported engine information
SAP/ui5-tooling-extensions pull request #94
Opened 2023-05-12 13:10 UTC by flovogt

2023-05-15 09:11 UTC, matz3 commented
Thanks for looking up those versions! As the extension requires UI5 Tooling v3 I'd suggest to just also define `^16.18.0 || >=18.12.0`. I don't think we should define versions less than those.

2023-05-15 09:12 UTC, matz3 requested changes

2023-05-15 09:12 UTC, matz3 commented on package.json
> +		"node": ">=18",
Why is this different?

2023-05-15 09:19 UTC, flovogt commented on package.json
> +		"node": ">=18",
npm 9 is not included in node 16

2023-05-15 10:46 UTC, flovogt commented on package.json
> +		"node": ">=18",
but sure... some one could install npm manually to v9 and still use node 16

2023-05-22 14:25 UTC, matz3 approved these changes

2023-05-23 08:02 UTC, merged